language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

before_script:
  - npm install

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: "Run tests"
      script: npm run test
