language: node_js

node_js:
  - stable

before_script:
  - npm install @types/node --save-dev
  - yarn

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: "Run tests"
      script: yarn test
