language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: "Run tests"
      script: yarn test
